# 线上配置文件
# 
# 
server:
  port: 8101
spring:
  # 数据库配置
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-7srr6mpi.sql.tencentcdb.com:29063/lingxi?serverTimezone=Asia/Shanghai
    username: root
    password: Landada@20031125
  # Redis 配置
  
  redis:
    database: 1
    host: 8.137.105.75
    port: 6379
    timeout: 5000
    password: lingxi@12345678
  # Elasticsearch 配置
  
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档的配置
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.lingxi.lingxibackend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: root
    # Basic认证密码
    password: lingxi@12345678